### ISSUE TITLE
fill vacancies in open data liaison roster

### ISSUE THREAD

**Issue by haileypate** [cityofaustin/open-data-docs#15]
current gaps/vacancies are here: 
https://airtable.com/shruRN493vFUBcqPx

cc #14

**Comment by haileypate** [comment]
As of today, we have one more gap to fill for the liaison roster: Labor Relations. Our team is currently asking around the 'friends of open data' network to see if we can identify this person... cc @cpurma

**Comment by haileypate** [comment]
still have one more gap.. Labor Relations. sent another inquiry today, looking for a contact over there

**Comment by haileypate** [comment]
done! We now have 47 liaisons, covering all 38 departments identified in the City budget. Woot!

**Comment by mateoclarke** [comment]
:tada:
