### ISSUE TITLE
can we embed wiki content into github pages? 

### ISSUE THREAD

**Issue by haileypate** [cityofaustin/open-data-docs#19]
Let's try building our metadata standards in this repo's wiki. @thecrow1213, would it be possible to bring that wiki content in to the GitHub pages site at https://cityofaustin.github.io/open-data-docs/metadata.html ?

**Comment by haileypate** [comment]
link to some very early draft wiki content: https://github.com/cityofaustin/open-data-docs/wiki/Metadata-standard

**Comment by cpurma** [comment]
Looking good!

**Comment by haileypate** [comment]
hmm... now, in the case of the metadata standard....  i'm wondering if it's worth using the wiki over the repo itself. here's an example of using the repo to view a document's history: https://github.com/cityofaustin/open-data-docs/commits/gh-pages/plans/animal-services.md

looks pretty clean! 

only advantage i can see to using the wiki is the wysiwyg editor.. hmm, decisions, decisions.

**Comment by TheCrow1213** [comment]
@haileypate it turns out GitHub doesn't have an API to access wiki data... however if you want an easy solution for WYSIWYG editors for jekyll sites, prose.io or Cloud Cannon may be some services to check out...

prose.io: http://g.recordit.co/rxTJxoh1g2.gif
cloud cannon: http://g.recordit.co/7n18TtCcZ0.gif

**Comment by haileypate** [comment]
looks like we can get our needs met by editing the markdown files directly. thank you @TheCrow1213 for the recommendations on WYSYIWYG editors!

**Comment by TheCrow1213** [comment]
No prob! :)
